app:
  servicebus:
    # Works with the local Service Bus emulator
    connection-string: ${SERVICEBUS_CONNECTION_STRING:Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;}
    queue-name: ${SERVICEBUS_QUEUE_NAME:queue.1}
